# Code Intelligence Dashboard Configuration
# **Last Updated:** 2025-01-27 15:30:00

system:
  environment: development
  log_level: INFO
  timezone: UTC
  data_dir: data
  temp_dir: temp
  cache_dir: cache

processing:
  batch_size: 1000
  max_workers: 4
  memory_limit_gb: 8
  streaming_enabled: true
  parallel_processing: true
  checkpoint_interval: 10000
  error_tolerance: 0.01
  download_chunk_size: 8192
  download_timeout_seconds: 300
  download_progress_interval_bytes: 1048576
  file_download_chunk_size: 1024

graph_database:
  uri: bolt://localhost:7687
  user: neo4j
  password: neo4j
  database: dashboard
  max_connection_pool_size: 100
  connection_timeout: 30
  max_transaction_retry_time: 30

redis:
  url: redis://localhost:6379
  password: null
  db: 0
  decode_responses: true

logging:
  level: INFO
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name} | {file}:{line} | {message}"
  files:
    populate_db: "populate_db.log"
    dashboard: "dashboard.log"
  rotation: {}
  levels: {}
  handlers:
    - console
    - file
  encoding: "utf-8"

monitoring:
  metrics_enabled: true
  status_file: data/status/system_status.json
  history_file: data/status/status_history.json
  api_response_threshold_ms: 5000.0
  health_check_interval_seconds: 300
  metrics_collection_interval_seconds: 60
  alert_thresholds: {}
  alerts_enabled: false
  alert_channels: []

caching:
  enabled: true
  cache_directory: data/cache
  agency_list_ttl_days: 30
  data_dictionary_ttl_days: 30
  query_cache_ttl_hours: 24
  max_cache_size_mb: 1024

directories:
  data_root: data
  raw_data: data/raw
  processed_data: data/processed
  downloads: data/downloads
  cache: data/cache
  logs: logs
  temp: temp
  reports: data/reports
  backups: data/backups

validation:
  schema_directory: data/reference
  error_log_directory: logs/validation
  max_retries: 3
  retry_delay_seconds: 1.0
  validation_timeout_seconds: 30

development:
  debug_mode: false
  sample_data_size: 1000
  mock_api_responses: false

testing:
  test_data_path: tests/data
  mock_downloads: true
  skip_external_apis: true

output:
  verbosity: info
  styles: {}

process_validation:
  checkpoint_type: demo_verification
  checkpoint_operation: enhanced_demo

ui:
  theme: material
  port: 5007
  host: localhost
  auto_reload: true
  show_on_startup: true
  sizing_mode: stretch_width

visualization:
  default_plot_width: 800
  default_plot_height: 600
  color_palette:
    - "#1f77b4"
    - "#ff7f0e"
    - "#2ca02c"
    - "#d62728"
  max_data_points: 10000
  enable_tooltips: true
  enable_zoom: true

network_graph:
  default_layout: spring
  node_size_range:
    - 10
    - 50
  edge_width_range:
    - 1
    - 5
  max_nodes: 500
  clustering_enabled: true

analysis:
  exclude_dirs:
    - .venv
    - __pycache__
    - node_modules
    - .git
    - logs
    - outputs
    - htmlcov
    - docker
    - temp
    - cache
    - data/processed
    - data/test
    - data/reference
    - data/reports
    - data/manual_classifications.json
  max_query_limit: 1000
  complexity_threshold: 10
  enable_inheritance_analysis: true
  enable_dependency_analysis: true
  enable_metrics_calculation: true
  max_file_size_mb: 10

# File Analysis Configuration
file_analysis:
  include_patterns:
    - "*.py"
    - "*.js"
    - "*.html"
    - "*.css"
    - "*.md"
    - "*.json"
    - "*.yml"
    - "*.yaml"
  exclude_patterns:
    - "__pycache__"
    - "*.pyc"
    - "node_modules"
    - ".git"
    - ".vscode"
    - "*.egg-info"
    - "logs"
    - "temp"
    - "cache"
    - "data/processed"
    - "data/test"
  default_encoding: "utf-8"
  encoding_fallbacks:
    - "utf-8-sig"
    - "latin1"
    - "cp1252"
  max_file_size_mb: 10
  enable_caching: true
  cache_ttl_hours: 24

# AST Analysis Configuration
ast_analysis:
  complexity_base: 1
  complexity_increment: 1
  max_function_complexity: 50
  max_file_complexity: 100
  enable_relationship_extraction: true
  enable_pydantic_detection: true
  enable_decorator_analysis: true
  error_tolerance: true
  skip_syntax_errors: true
  progress_reporting_interval: 100

# Database Population Configuration
population:
  default_db_path: "code_intelligence.db"
  batch_processing: true
  batch_size: 1000
  progress_reporting: true
  progress_interval: 100
  error_logging: true
  clear_existing_data: true
  enable_relationship_resolution: true
  enable_cross_file_analysis: true
  max_concurrent_files: 10

# Legacy compatibility fields
log_level: INFO
log_file: dashboard.log
db_path: code_intelligence.db
